steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/astute-winter-373022/predictions', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/astute-winter-373022/predictions']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'bplpredictions', '--image', 'gcr.io/astute-winter-373022/predictions', '--region', 'us-west1']
images:
- gcr.io/astute-winter-373022/predictions